nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.9.2.cjs

# Compatibility settings
enableGlobalCache: false
enableScripts: true
enableStrictSsl: true
enableNetwork: true

# Dependency resolution
packageExtensions:
  "@react-native-community/cli-platform-android@*":
    dependencies:
      "@react-native-community/cli-tools": "*"
  "@react-native-community/cli-platform-ios@*":
    dependencies:
      "@react-native-community/cli-tools": "*"

# Peer dependency handling
supportedArchitectures:
  os: ["current"]
  cpu: ["current"]

# Install behavior
preferInteractive: false
enableImmutableInstalls: false
enableMirror: false

# Network settings
httpTimeout: 60000
httpRetry: 3
